### ISSUE TITLE
Implement: price promotion on `appointment_service`

### ISSUE THREAD

**Issue by ziadab** [ilyasma/yukki#2]
Feature

Salon owners like to apply a reduction on certain services for certain clients in place

they also have seasonal promotions for a set of services by %

Problems

we need to do it in a way that it would be possible for us to calculate the earnings in the dashboard

besides the future promotion pages, this also needs to be done in place in appointment creation/edit pages (this needs to be done as soon as possible)

Suggested solutions

The actual price stays in `service` and the after promotion/reduction price should be in `appointment_service`(that’s the relation table between `appointment` and `services`)

**Comment by ziadab** [comment]
Hiiii

**Comment by ilyasma** [comment]
Hiiiii

**Comment by ziadab** [comment]
suup
